"""catalogo

Revision ID: 46cbe513f73a
Revises: 31209ead30ce
Create Date: 2026-10-06 01:14:25.199605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46cbe513f73a'
down_revision: Union[str, Sequence[str], None] = '31209ead30ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categoria')),
    sa.UniqueConstraint('slug', name=op.f('uq_categoria_slug'))
    )
    op.create_table('estado',
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.Column('perfil_padrao', sa.Enum('quente', 'moderado', 'frio', name='perfilcodigo', native_enum=False, length=30), nullable=False),
    sa.PrimaryKeyConstraint('uf', name=op.f('pk_estado'))
    )
    op.create_table('fase_roteiro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('referencia', sa.Enum('gestacao_semana', 'bebe_mes', name='referenciafase', native_enum=False, length=30), nullable=False),
    sa.Column('inicio', sa.Integer(), nullable=False),
    sa.Column('fim', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.CheckConstraint('fim >= inicio', name=op.f('ck_fase_roteiro_intervalo_valido')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fase_roteiro')),
    sa.UniqueConstraint('codigo', name=op.f('uq_fase_roteiro_codigo'))
    )
    op.create_table('janela_tamanho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tamanho', sa.Enum('RN', 'P', 'M', 'G', 'GG', name='tamanho', native_enum=False, length=30), nullable=False),
    sa.Column('idade_inicio_dias', sa.Integer(), nullable=False),
    sa.Column('idade_fim_dias', sa.Integer(), nullable=False),
    sa.Column('peso_referencia', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_janela_tamanho')),
    sa.UniqueConstraint('tamanho', name=op.f('uq_janela_tamanho_tamanho'))
    )
    op.create_table('marca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('faixa_padrao', sa.Enum('economico', 'intermediario', 'investir', name='faixa', native_enum=False, length=30), nullable=False),
    sa.Column('validado', sa.Boolean(), nullable=False),
    sa.Column('fonte', sa.Text(), nullable=True),
    sa.Column('revisado_em', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marca')),
    sa.UniqueConstraint('nome', name=op.f('uq_marca_nome'))
    )
    op.create_table('perfil_clima',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.Enum('quente', 'moderado', 'frio', name='perfilcodigo', native_enum=False, length=30), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('meses_frios', sa.JSON(), nullable=False),
    sa.Column('meses_frescos', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_perfil_clima')),
    sa.UniqueConstraint('codigo', name=op.f('uq_perfil_clima_codigo'))
    )
    op.create_table('regra_seguranca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=60), nullable=False),
    sa.Column('tema', sa.Enum('sono', 'transporte', 'banho', 'alimentacao', 'casa', 'brinquedos', 'geral', name='temaseguranca', native_enum=False, length=30), nullable=False),
    sa.Column('idade_inicio_meses', sa.Integer(), nullable=False),
    sa.Column('idade_fim_meses', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('base', sa.String(length=120), nullable=False),
    sa.Column('validado', sa.Boolean(), nullable=False),
    sa.Column('fonte', sa.Text(), nullable=True),
    sa.Column('revisado_em', sa.Date(), nullable=True),
    sa.CheckConstraint('idade_fim_meses >= idade_inicio_meses', name=op.f('ck_regra_seguranca_intervalo_valido')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regra_seguranca')),
    sa.UniqueConstraint('codigo', name=op.f('uq_regra_seguranca_codigo'))
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('fase_compra_id', sa.Integer(), nullable=False),
    sa.Column('para_que_serve', sa.Text(), nullable=False),
    sa.Column('como_escolher', sa.Text(), nullable=False),
    sa.Column('idade_inicio_meses', sa.Integer(), nullable=False),
    sa.Column('prioridade_base', sa.Enum('essencial', 'util', 'pode_esperar', name='prioridade', native_enum=False, length=30), nullable=False),
    sa.Column('e_seguranca', sa.Boolean(), nullable=False),
    sa.Column('uso_clima', sa.Enum('neutro', 'divide', 'so_frio', name='usoclima', native_enum=False, length=30), nullable=False),
    sa.Column('variante_frio', sa.String(length=60), nullable=True),
    sa.Column('variante_calor', sa.String(length=60), nullable=True),
    sa.Column('escala_lavagem', sa.Boolean(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('unidade_texto', sa.String(length=120), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.CheckConstraint("uso_clima <> 'divide' OR (variante_frio IS NOT NULL AND variante_calor IS NOT NULL)", name=op.f('ck_item_variantes_obrigatorias')),
    sa.CheckConstraint('quantidade IS NULL OR quantidade >= 1', name=op.f('ck_item_quantidade_positiva')),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], name=op.f('fk_item_categoria_id_categoria')),
    sa.ForeignKeyConstraint(['fase_compra_id'], ['fase_roteiro.id'], name=op.f('fk_item_fase_compra_id_fase_roteiro')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item')),
    sa.UniqueConstraint('slug', name=op.f('uq_item_slug'))
    )
    op.create_table('municipio',
    sa.Column('codigo_ibge', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('nome_busca', sa.String(length=80), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('perfil_excecao', sa.Enum('quente', 'moderado', 'frio', name='perfilcodigo', native_enum=False, length=30), nullable=True),
    sa.ForeignKeyConstraint(['uf'], ['estado.uf'], name=op.f('fk_municipio_uf_estado')),
    sa.PrimaryKeyConstraint('codigo_ibge', name=op.f('pk_municipio'))
    )
    op.create_index(op.f('ix_municipio_nome_busca'), 'municipio', ['nome_busca'], unique=False)
    op.create_table('item_marca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('marca_id', sa.Integer(), nullable=False),
    sa.Column('faixa', sa.Enum('economico', 'intermediario', 'investir', name='faixa', native_enum=False, length=30), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name=op.f('fk_item_marca_item_id_item'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['marca_id'], ['marca.id'], name=op.f('fk_item_marca_marca_id_marca'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_marca')),
    sa.UniqueConstraint('item_id', 'marca_id', name=op.f('uq_item_marca_item_id'))
    )
    op.create_table('item_regra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('condicao', sa.Enum('com_carro', 'sem_carro', 'apartamento', 'casa_sem_escada', 'casa_com_escada', 'perfil_quente', 'perfil_moderado', 'perfil_frio', name='condicao', native_enum=False, length=30), nullable=False),
    sa.Column('efeito', sa.Enum('incluir_so_se', 'mudar_prioridade', 'dica', name='efeito', native_enum=False, length=30), nullable=False),
    sa.Column('valor', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name=op.f('fk_item_regra_item_id_item'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_regra')),
    sa.UniqueConstraint('item_id', 'condicao', 'efeito', name=op.f('uq_item_regra_item_id'))
    )
    op.create_table('item_regra_seguranca',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('regra_seguranca_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name=op.f('fk_item_regra_seguranca_item_id_item'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['regra_seguranca_id'], ['regra_seguranca.id'], name=op.f('fk_item_regra_seguranca_regra_seguranca_id_regra_seguranca'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'regra_seguranca_id', name=op.f('pk_item_regra_seguranca'))
    )
    op.create_table('item_tamanho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('tamanho', sa.Enum('RN', 'P', 'M', 'G', 'GG', name='tamanho', native_enum=False, length=30), nullable=False),
    sa.Column('quantidade_base', sa.Integer(), nullable=False),
    sa.Column('fase_compra_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('quantidade_base >= 0', name=op.f('ck_item_tamanho_quantidade_nao_negativa')),
    sa.ForeignKeyConstraint(['fase_compra_id'], ['fase_roteiro.id'], name=op.f('fk_item_tamanho_fase_compra_id_fase_roteiro')),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name=op.f('fk_item_tamanho_item_id_item'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_tamanho')),
    sa.UniqueConstraint('item_id', 'tamanho', name=op.f('uq_item_tamanho_item_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_tamanho')
    op.drop_table('item_regra_seguranca')
    op.drop_table('item_regra')
    op.drop_table('item_marca')
    op.drop_index(op.f('ix_municipio_nome_busca'), table_name='municipio')
    op.drop_table('municipio')
    op.drop_table('item')
    op.drop_table('regra_seguranca')
    op.drop_table('perfil_clima')
    op.drop_table('marca')
    op.drop_table('janela_tamanho')
    op.drop_table('fase_roteiro')
    op.drop_table('estado')
    op.drop_table('categoria')
    # ### end Alembic commands ###
