"""familia

Revision ID: f17f5e46e3e3
Revises: 46cbe513f73a
Create Date: 2026-10-06 01:15:33.540158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f17f5e46e3e3'
down_revision: Union[str, Sequence[str], None] = '46cbe513f73a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enxoval',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('municipio_codigo', sa.Integer(), nullable=False),
    sa.Column('perfil_clima', sa.Enum('quente', 'moderado', 'frio', name='perfilcodigo', native_enum=False, length=30), nullable=False),
    sa.Column('perfil_corrigido', sa.Boolean(), nullable=False),
    sa.Column('data_prevista', sa.Date(), nullable=False),
    sa.Column('dias_entre_lavagens', sa.SmallInteger(), nullable=False),
    sa.Column('moradia', sa.Enum('apartamento', 'casa_sem_escada', 'casa_com_escada', name='moradia', native_enum=False, length=30), nullable=False),
    sa.Column('tem_carro', sa.Boolean(), nullable=False),
    sa.Column('orcamento', sa.Enum('economico', 'intermediario', 'investir', name='faixa', native_enum=False, length=30), nullable=False),
    sa.Column('primeiro_filho', sa.Boolean(), nullable=False),
    sa.CheckConstraint('dias_entre_lavagens BETWEEN 1 AND 7', name=op.f('ck_enxoval_dias_entre_lavagens_valido')),
    sa.ForeignKeyConstraint(['municipio_codigo'], ['municipio.codigo_ibge'], name=op.f('fk_enxoval_municipio_codigo_municipio')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enxoval'))
    )
    op.create_table('enxoval_linha',
    sa.Column('enxoval_id', sa.Uuid(), nullable=False),
    sa.Column('chave', sa.String(length=140), nullable=False),
    sa.Column('qtd_comprada', sa.Integer(), nullable=False),
    sa.Column('qtd_ganhada', sa.Integer(), nullable=False),
    sa.Column('qtd_ja_tinha', sa.Integer(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('qtd_comprada >= 0 AND qtd_ganhada >= 0 AND qtd_ja_tinha >= 0', name=op.f('ck_enxoval_linha_quantidades_nao_negativas')),
    sa.ForeignKeyConstraint(['enxoval_id'], ['enxoval.id'], name=op.f('fk_enxoval_linha_enxoval_id_enxoval'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('enxoval_id', 'chave', name=op.f('pk_enxoval_linha'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enxoval_linha')
    op.drop_table('enxoval')
    # ### end Alembic commands ###
