/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/saude": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Saude */
        get: operations["saude_api_v1_saude_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/perfis-clima": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Perfis */
        get: operations["listar_perfis_api_v1_perfis_clima_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/municipios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar Municipios
         * @description Autocompletar de cidade. Casa por prefixo do nome ou de qualquer palavra dele.
         */
        get: operations["buscar_municipios_api_v1_municipios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enxovais": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Criar */
        post: operations["criar_api_v1_enxovais_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enxovais/{enxoval_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ler */
        get: operations["ler_api_v1_enxovais__enxoval_id__get"];
        put?: never;
        post?: never;
        /** Apagar */
        delete: operations["apagar_api_v1_enxovais__enxoval_id__delete"];
        options?: never;
        head?: never;
        /**
         * Editar
         * @description Recebe as 6 respostas inteiras; não há edição parcial no MVP.
         */
        patch: operations["editar_api_v1_enxovais__enxoval_id__patch"];
        trace?: never;
    };
    "/api/v1/enxovais/{enxoval_id}/linhas/{chave}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Marcar
         * @description Grava as quantidades da linha e devolve a lista e o progresso já atualizados.
         */
        put: operations["marcar_api_v1_enxovais__enxoval_id__linhas__chave__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enxovais/{enxoval_id}/linhas/{chave}/completar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Completar */
        post: operations["completar_api_v1_enxovais__enxoval_id__linhas__chave__completar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertaSaida */
        AlertaSaida: {
            /** Codigo */
            codigo: string;
            tema: components["schemas"]["TemaSeguranca"];
            /** Texto */
            texto: string;
            /** Base */
            base: string;
            /**
             * Ativo A Partir
             * Format: date
             */
            ativo_a_partir: string;
            /**
             * Ativo Ate
             * Format: date
             */
            ativo_ate: string;
            /** Itens */
            itens: string[];
        };
        /** CategoriaSaida */
        CategoriaSaida: {
            /** Slug */
            slug: string;
            /** Nome */
            nome: string;
            /** Ordem */
            ordem: number;
        };
        /** CompletarEntrada */
        CompletarEntrada: {
            /** Origem */
            origem: string;
        };
        /** EnxovalCriado */
        EnxovalCriado: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** EnxovalSaida */
        EnxovalSaida: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            respostas: components["schemas"]["RespostasSaida"];
            /** Categorias */
            categorias: components["schemas"]["CategoriaSaida"][];
            /** Linhas */
            linhas: components["schemas"]["LinhaSaida"][];
            /** Linhas Fora Da Lista */
            linhas_fora_da_lista: components["schemas"]["LinhaForaSaida"][];
            /** Fichas */
            fichas: components["schemas"]["FichaSaida"][];
            /** Roteiro */
            roteiro: components["schemas"]["FaseSaida"][];
            /** Alertas */
            alertas: components["schemas"]["AlertaSaida"][];
            resumo: components["schemas"]["ResumoSaida"];
            progresso: components["schemas"]["ProgressoSaida"];
        };
        /** Erro */
        Erro: {
            /** Erro */
            erro: string;
            /** Mensagem */
            mensagem: string;
        };
        /**
         * Faixa
         * @enum {string}
         */
        Faixa: "economico" | "intermediario" | "investir";
        /** FaseSaida */
        FaseSaida: {
            /** Codigo */
            codigo: string;
            /** Nome */
            nome: string;
            /** Texto */
            texto: string;
            /**
             * Inicio
             * Format: date
             */
            inicio: string;
            /**
             * Fim
             * Format: date
             */
            fim: string;
            /** Atual */
            atual: boolean;
        };
        /** FichaSaida */
        FichaSaida: {
            /** Slug */
            slug: string;
            /** Nome */
            nome: string;
            /** Para Que Serve */
            para_que_serve: string;
            /** Como Escolher */
            como_escolher: string;
            /** Idade Inicio Meses */
            idade_inicio_meses: number;
            marcas: components["schemas"]["MarcasSaida"];
            /** Dicas */
            dicas: string[];
            /** Regras Seguranca */
            regras_seguranca: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LinhaForaSaida */
        LinhaForaSaida: {
            /** Chave */
            chave: string;
            /** Comprada */
            comprada: number;
            /** Ganhada */
            ganhada: number;
            /** Ja Tinha */
            ja_tinha: number;
        };
        /**
         * MomentoCompra
         * @enum {string}
         */
        MomentoCompra: "atrasado" | "agora" | "proxima_fase" | "futuro";
        /** LinhaSaida */
        LinhaSaida: {
            /** Chave */
            chave: string;
            /** Item Slug */
            item_slug: string;
            /** Nome */
            nome: string;
            /** Rotulo Variante */
            rotulo_variante: string | null;
            /** Categoria Slug */
            categoria_slug: string;
            tamanho: components["schemas"]["Tamanho"] | null;
            /** Quantidade */
            quantidade: number;
            /** Unidade Texto */
            unidade_texto: string | null;
            prioridade: components["schemas"]["Prioridade"];
            /** Fase Codigo */
            fase_codigo: string;
            momento_compra: components["schemas"]["MomentoCompra"];
            /** E Seguranca */
            e_seguranca: boolean;
            /** Comprada */
            comprada: number;
            /** Ganhada */
            ganhada: number;
            /** Ja Tinha */
            ja_tinha: number;
            /** Faltam */
            faltam: number;
        };
        /** MarcacaoEntrada */
        MarcacaoEntrada: {
            /** Comprada */
            comprada: number;
            /** Ganhada */
            ganhada: number;
            /** Ja Tinha */
            ja_tinha: number;
        };
        /** MarcasSaida */
        MarcasSaida: {
            /** Nomes */
            nomes: string[];
            faixa: components["schemas"]["Faixa"] | null;
            /** Faixa Aproximada */
            faixa_aproximada: boolean;
        };
        /**
         * Moradia
         * @enum {string}
         */
        Moradia: "apartamento" | "casa_sem_escada" | "casa_com_escada";
        /** MunicipioBuscaSaida */
        MunicipioBuscaSaida: {
            /** Codigo Ibge */
            codigo_ibge: number;
            /** Nome */
            nome: string;
            /** Uf */
            uf: string;
            perfil_sugerido: components["schemas"]["PerfilCodigo"];
        };
        /** MunicipioSaida */
        MunicipioSaida: {
            /** Codigo Ibge */
            codigo_ibge: number;
            /** Nome */
            nome: string;
            /** Uf */
            uf: string;
        };
        /**
         * PerfilCodigo
         * @enum {string}
         */
        PerfilCodigo: "quente" | "moderado" | "frio";
        /** PerfilSaida */
        PerfilSaida: {
            codigo: components["schemas"]["PerfilCodigo"];
            /** Nome */
            nome: string;
            /** Descricao */
            descricao: string;
            /** Meses Frios */
            meses_frios: number[];
            /** Meses Frescos */
            meses_frescos: number[];
        };
        /**
         * Prioridade
         * @enum {string}
         */
        Prioridade: "essencial" | "util" | "pode_esperar";
        /** ProgressoSaida */
        ProgressoSaida: {
            /** Total Unidades */
            total_unidades: number;
            /** Atendidas */
            atendidas: number;
            /** Faltam */
            faltam: number;
            /** Percentual */
            percentual: number;
        };
        /** RespostasEntrada */
        RespostasEntrada: {
            /** Municipio Codigo */
            municipio_codigo: number;
            /**
             * Data Prevista
             * Format: date
             */
            data_prevista: string;
            /** Dias Entre Lavagens */
            dias_entre_lavagens: number;
            moradia: components["schemas"]["Moradia"];
            /** Tem Carro */
            tem_carro: boolean;
            orcamento: components["schemas"]["Faixa"];
            /** Primeiro Filho */
            primeiro_filho: boolean;
            correcao_perfil?: components["schemas"]["PerfilCodigo"] | null;
        };
        /** RespostasSaida */
        RespostasSaida: {
            municipio: components["schemas"]["MunicipioSaida"];
            perfil_clima: components["schemas"]["PerfilCodigo"];
            /** Perfil Corrigido */
            perfil_corrigido: boolean;
            /**
             * Data Prevista
             * Format: date
             */
            data_prevista: string;
            /** Dias Entre Lavagens */
            dias_entre_lavagens: number;
            moradia: components["schemas"]["Moradia"];
            /** Tem Carro */
            tem_carro: boolean;
            orcamento: components["schemas"]["Faixa"];
            /** Primeiro Filho */
            primeiro_filho: boolean;
        };
        /** ResumoSaida */
        ResumoSaida: {
            /** Dias Sem Lavar */
            dias_sem_lavar: number;
            /** Total Unidades */
            total_unidades: number;
            /** Aviso Volume Alto */
            aviso_volume_alto: boolean;
            /** Destacar Ja Tinha */
            destacar_ja_tinha: boolean;
        };
        /**
         * Tamanho
         * @enum {string}
         */
        Tamanho: "RN" | "P" | "M" | "G" | "GG";
        /**
         * TemaSeguranca
         * @enum {string}
         */
        TemaSeguranca: "sono" | "transporte" | "banho" | "alimentacao" | "casa" | "brinquedos" | "geral";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    saude_api_v1_saude_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    listar_perfis_api_v1_perfis_clima_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerfilSaida"][];
                };
            };
        };
    };
    buscar_municipios_api_v1_municipios_get: {
        parameters: {
            query: {
                busca: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MunicipioBuscaSaida"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    criar_api_v1_enxovais_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RespostasEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnxovalCriado"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    ler_api_v1_enxovais__enxoval_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                enxoval_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnxovalSaida"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    apagar_api_v1_enxovais__enxoval_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                enxoval_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    editar_api_v1_enxovais__enxoval_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                enxoval_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RespostasEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnxovalSaida"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    marcar_api_v1_enxovais__enxoval_id__linhas__chave__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                enxoval_id: string;
                /** @description <slug>:<tamanho>:<variante>, ex.: body:P:frio */
                chave: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarcacaoEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnxovalSaida"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    completar_api_v1_enxovais__enxoval_id__linhas__chave__completar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                enxoval_id: string;
                /** @description <slug>:<tamanho>:<variante>, ex.: body:P:frio */
                chave: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompletarEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnxovalSaida"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
}
