/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/saude": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Saude */
        get: operations["saude_api_v1_saude_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/perfis-clima": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Perfis */
        get: operations["listar_perfis_api_v1_perfis_clima_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/municipios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar Municipios
         * @description Autocompletar de cidade. Casa por prefixo do nome ou de qualquer palavra dele.
         */
        get: operations["buscar_municipios_api_v1_municipios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enxovais": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar
         * @description Lista os enxovais do dono com o mesmo progresso exibido na planilha.
         */
        get: operations["listar_api_v1_enxovais_get"];
        put?: never;
        /**
         * Criar
         * @description Cria um enxoval a partir das respostas do questionário.
         *
         *     Aplica rate limiting por IP (20 criações/hora) para evitar abuso.
         *     Retorna o UUID gerado no cabeçalho ``Location`` além do corpo.
         */
        post: operations["criar_api_v1_enxovais_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enxovais/{enxoval_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ler
         * @description Retorna o enxoval completo: linhas calculadas, roteiro, fichas e progresso.
         */
        get: operations["ler_api_v1_enxovais__enxoval_id__get"];
        put?: never;
        post?: never;
        /**
         * Apagar
         * @description Remove permanentemente o enxoval e todas as suas linhas.
         */
        delete: operations["apagar_api_v1_enxovais__enxoval_id__delete"];
        options?: never;
        head?: never;
        /**
         * Editar
         * @description Substitui todas as respostas do questionário. Marcações são preservadas.
         */
        patch: operations["editar_api_v1_enxovais__enxoval_id__patch"];
        trace?: never;
    };
    "/api/v1/enxovais/{enxoval_id}/prever": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Prever
         * @description Calcula uma prévia sem persistir respostas nem alterar marcações.
         */
        post: operations["prever_api_v1_enxovais__enxoval_id__prever_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enxovais/{enxoval_id}/linhas/{chave}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Marcar
         * @description Grava as quantidades da linha e devolve a lista e o progresso atualizados.
         */
        put: operations["marcar_api_v1_enxovais__enxoval_id__linhas__chave__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enxovais/{enxoval_id}/linhas/{chave}/completar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Completar
         * @description Completa o que falta na linha com a origem informada e devolve o estado atualizado.
         */
        post: operations["completar_api_v1_enxovais__enxoval_id__linhas__chave__completar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enxovais/{enxoval_id}/exportar.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Exportar Csv
         * @description Exporta a planilha em CSV com BOM UTF-8 para compatibilidade com Excel.
         */
        get: operations["exportar_csv_api_v1_enxovais__enxoval_id__exportar_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enxovais/{enxoval_id}/exportar.xlsx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Exportar Xlsx
         * @description Exporta a planilha em XLSX com abas Planilha e Roteiro.
         */
        get: operations["exportar_xlsx_api_v1_enxovais__enxoval_id__exportar_xlsx_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enxovais/{enxoval_id}/exportar.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Exportar Pdf
         * @description Exporta a planilha em PDF via WeasyPrint com template HTML.
         */
        get: operations["exportar_pdf_api_v1_enxovais__enxoval_id__exportar_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/perfil": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ler */
        get: operations["ler_api_v1_perfil_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/perfil/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Salvar Avatar */
        put: operations["salvar_avatar_api_v1_perfil_avatar_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AlertaSaida
         * @description Alerta de segurança com a data a partir da qual passa a ser relevante.
         */
        AlertaSaida: {
            /** Codigo */
            codigo: string;
            tema: components["schemas"]["TemaSeguranca"];
            /** Texto */
            texto: string;
            /** Base */
            base: string;
            /**
             * Ativo A Partir
             * Format: date
             */
            ativo_a_partir: string;
            /**
             * Ativo Ate
             * Format: date
             */
            ativo_ate: string;
            /** Itens */
            itens: string[];
        };
        /** AvatarEntrada */
        AvatarEntrada: {
            /** Avatar */
            avatar: ("ursinho" | "coelhinho" | "elefantinho" | "patinho" | "nuvem" | "lua") | null;
        };
        /**
         * CategoriaSaida
         * @description Categoria de itens do catálogo (ex.: Roupas, Higiene).
         */
        CategoriaSaida: {
            /** Slug */
            slug: string;
            /** Nome */
            nome: string;
            /** Ordem */
            ordem: number;
        };
        /**
         * CompletarEntrada
         * @description Origem para completar o que falta em uma linha (marcar tudo).
         */
        CompletarEntrada: {
            /**
             * Origem
             * @description Como contabilizar o restante: 'comprada', 'ganhada' ou 'ja_tinha'.
             */
            origem: string;
        };
        /**
         * EnxovalCriado
         * @description Resposta de criação de enxoval: apenas o UUID gerado.
         */
        EnxovalCriado: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /**
         * EnxovalResumo
         * @description Resumo de um enxoval para a tela 'Meus enxovais' — sem linhas calculadas.
         */
        EnxovalResumo: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Municipio Nome */
            municipio_nome: string;
            /** Municipio Uf */
            municipio_uf: string;
            /**
             * Data Prevista
             * Format: date
             */
            data_prevista: string;
            /** Percentual Progresso */
            percentual_progresso: number;
        };
        /**
         * EnxovalSaida
         * @description Enxoval completo: respostas, lista calculada, roteiro, fichas e progresso.
         */
        EnxovalSaida: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            respostas: components["schemas"]["RespostasSaida"];
            /** Categorias */
            categorias: components["schemas"]["CategoriaSaida"][];
            /** Linhas */
            linhas: components["schemas"]["LinhaSaida"][];
            /** Linhas Fora Da Lista */
            linhas_fora_da_lista: components["schemas"]["LinhaForaSaida"][];
            /** Fichas */
            fichas: components["schemas"]["FichaSaida"][];
            /** Roteiro */
            roteiro: components["schemas"]["FaseSaida"][];
            /** Alertas */
            alertas: components["schemas"]["AlertaSaida"][];
            resumo: components["schemas"]["ResumoSaida"];
            progresso: components["schemas"]["ProgressoSaida"];
        };
        /**
         * Erro
         * @description Resposta de erro padrão da API.
         *
         *     Attributes:
         *         erro: Código de erro em snake_case (ex.: ``enxoval_nao_encontrado``).
         *         mensagem: Mensagem legível em português para exibição na tela.
         */
        Erro: {
            /** Erro */
            erro: string;
            /** Mensagem */
            mensagem: string;
        };
        /**
         * Faixa
         * @enum {string}
         */
        Faixa: "economico" | "intermediario" | "investir";
        /**
         * FaseSaida
         * @description Uma fase do roteiro de compras com datas calculadas a partir da data prevista.
         */
        FaseSaida: {
            /** Codigo */
            codigo: string;
            /** Nome */
            nome: string;
            /** Texto */
            texto: string;
            /**
             * Inicio
             * Format: date
             */
            inicio: string;
            /**
             * Fim
             * Format: date
             */
            fim: string;
            /** Atual */
            atual: boolean;
        };
        /**
         * FichaSaida
         * @description Ficha informativa de um item: o que é, como escolher, marcas e alertas.
         */
        FichaSaida: {
            /** Slug */
            slug: string;
            /** Nome */
            nome: string;
            /** Para Que Serve */
            para_que_serve: string;
            /** Como Escolher */
            como_escolher: string;
            /** Idade Inicio Meses */
            idade_inicio_meses: number;
            marcas: components["schemas"]["MarcasSaida"];
            /** Dicas */
            dicas: string[];
            /** Regras Seguranca */
            regras_seguranca: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LinhaForaSaida
         * @description Linha marcada pela família que não está mais na lista calculada atual.
         */
        LinhaForaSaida: {
            /** Chave */
            chave: string;
            /** Nome */
            nome?: string | null;
            /** Tamanho */
            tamanho?: string | null;
            /** Rotulo Variante */
            rotulo_variante?: string | null;
            /** Comprada */
            comprada: number;
            /** Ganhada */
            ganhada: number;
            /** Ja Tinha */
            ja_tinha: number;
        };
        /**
         * LinhaSaida
         * @description Uma linha da planilha: item calculado pelo motor mesclado com as marcações da família.
         */
        LinhaSaida: {
            /** Chave */
            chave: string;
            /** Item Slug */
            item_slug: string;
            /** Nome */
            nome: string;
            /** Rotulo Variante */
            rotulo_variante: string | null;
            /** Categoria Slug */
            categoria_slug: string;
            tamanho: components["schemas"]["Tamanho"] | null;
            /** Quantidade */
            quantidade: number;
            /** Unidade Texto */
            unidade_texto: string | null;
            prioridade: components["schemas"]["Prioridade"];
            /** Fase Codigo */
            fase_codigo: string;
            /** E Seguranca */
            e_seguranca: boolean;
            /** Comprada */
            comprada: number;
            /** Ganhada */
            ganhada: number;
            /** Ja Tinha */
            ja_tinha: number;
            /** Faltam */
            faltam: number;
            momento_compra: components["schemas"]["MomentoCompra"];
        };
        /**
         * MarcacaoEntrada
         * @description Quantidades marcadas pela família para uma linha da planilha.
         *
         *     O limite de 9999 por campo evita que uma quantidade absurda cause overflow
         *     no banco, devolvendo 422 ao invés de 500.
         */
        MarcacaoEntrada: {
            /**
             * Comprada
             * @description Unidades compradas pela família.
             */
            comprada: number;
            /**
             * Ganhada
             * @description Unidades ganhas (chá de bebê, etc.).
             */
            ganhada: number;
            /**
             * Ja Tinha
             * @description Unidades que já existiam em casa.
             */
            ja_tinha: number;
        };
        /**
         * MarcasSaida
         * @description Marcas sugeridas para um item, já filtradas pelo orçamento da família.
         */
        MarcasSaida: {
            /** Nomes */
            nomes: string[];
            faixa: components["schemas"]["Faixa"] | null;
            /** Faixa Aproximada */
            faixa_aproximada: boolean;
        };
        /**
         * MomentoCompra
         * @enum {string}
         */
        MomentoCompra: "atrasado" | "agora" | "proxima_fase" | "futuro";
        /**
         * Moradia
         * @enum {string}
         */
        Moradia: "apartamento" | "casa_sem_escada" | "casa_com_escada";
        /** MunicipioBuscaSaida */
        MunicipioBuscaSaida: {
            /** Codigo Ibge */
            codigo_ibge: number;
            /** Nome */
            nome: string;
            /** Uf */
            uf: string;
            perfil_sugerido: components["schemas"]["PerfilCodigo"];
        };
        /**
         * MunicipioSaida
         * @description Dados do município do enxoval.
         */
        MunicipioSaida: {
            /** Codigo Ibge */
            codigo_ibge: number;
            /** Nome */
            nome: string;
            /** Uf */
            uf: string;
        };
        /**
         * PerfilCodigo
         * @enum {string}
         */
        PerfilCodigo: "quente" | "moderado" | "frio";
        /**
         * Prioridade
         * @enum {string}
         */
        Prioridade: "essencial" | "util" | "pode_esperar";
        /**
         * ProgressoSaida
         * @description Progresso de compras da família em relação ao total calculado.
         */
        ProgressoSaida: {
            /** Total Unidades */
            total_unidades: number;
            /** Atendidas */
            atendidas: number;
            /** Faltam */
            faltam: number;
            /** Percentual */
            percentual: number;
        };
        /**
         * RespostasEntrada
         * @description Respostas do questionário enviadas pelo cliente para criar ou editar um enxoval.
         */
        RespostasEntrada: {
            /**
             * Municipio Codigo
             * @description Código IBGE do município.
             */
            municipio_codigo: number;
            /**
             * Data Prevista
             * Format: date
             * @description Data prevista de nascimento (AAAA-MM-DD).
             */
            data_prevista: string;
            /**
             * Dias Entre Lavagens
             * @description Frequência de lavagem de roupas.
             */
            dias_entre_lavagens: number;
            /** @description Tipo de moradia da família. */
            moradia: components["schemas"]["Moradia"];
            /**
             * Tem Carro
             * @description A família tem carro próprio.
             */
            tem_carro: boolean;
            /** @description Faixa de orçamento para compras. */
            orcamento: components["schemas"]["Faixa"];
            /**
             * Primeiro Filho
             * @description É o primeiro filho da família.
             */
            primeiro_filho: boolean;
            /** @description Correção manual do perfil de clima (sobrescreve o padrão da cidade). */
            correcao_perfil?: components["schemas"]["PerfilCodigo"] | null;
        };
        /**
         * RespostasSaida
         * @description Respostas do questionário persistidas, enriquecidas com dados do município.
         */
        RespostasSaida: {
            municipio: components["schemas"]["MunicipioSaida"];
            perfil_clima: components["schemas"]["PerfilCodigo"];
            /** Perfil Corrigido */
            perfil_corrigido: boolean;
            /**
             * Data Prevista
             * Format: date
             */
            data_prevista: string;
            /** Dias Entre Lavagens */
            dias_entre_lavagens: number;
            moradia: components["schemas"]["Moradia"];
            /** Tem Carro */
            tem_carro: boolean;
            orcamento: components["schemas"]["Faixa"];
            /** Primeiro Filho */
            primeiro_filho: boolean;
        };
        /**
         * ResumoSaida
         * @description Resumo quantitativo da planilha.
         */
        ResumoSaida: {
            /** Dias Sem Lavar */
            dias_sem_lavar: number;
            /** Total Unidades */
            total_unidades: number;
            /** Aviso Volume Alto */
            aviso_volume_alto: boolean;
            /** Destacar Ja Tinha */
            destacar_ja_tinha: boolean;
        };
        /**
         * Tamanho
         * @enum {string}
         */
        Tamanho: "RN" | "P" | "M" | "G" | "GG";
        /**
         * TemaSeguranca
         * @enum {string}
         */
        TemaSeguranca: "sono" | "transporte" | "banho" | "alimentacao" | "casa" | "brinquedos" | "geral";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** PerfilSaida */
        app__rotas__perfil__PerfilSaida: {
            /**
             * Avatar
             * @default ursinho
             */
            avatar: ("ursinho" | "coelhinho" | "elefantinho" | "patinho" | "nuvem" | "lua") | null;
        };
        /**
         * PerfilSaida
         * @description Perfil de clima com suas características sazonais.
         */
        app__rotas__schemas__PerfilSaida: {
            codigo: components["schemas"]["PerfilCodigo"];
            /** Nome */
            nome: string;
            /** Descricao */
            descricao: string;
            /** Meses Frios */
            meses_frios: number[];
            /** Meses Frescos */
            meses_frescos: number[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    saude_api_v1_saude_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    listar_perfis_api_v1_perfis_clima_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__rotas__schemas__PerfilSaida"][];
                };
            };
        };
    };
    buscar_municipios_api_v1_municipios_get: {
        parameters: {
            query: {
                busca: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MunicipioBuscaSaida"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_api_v1_enxovais_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnxovalResumo"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    criar_api_v1_enxovais_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RespostasEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnxovalCriado"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    ler_api_v1_enxovais__enxoval_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                enxoval_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnxovalSaida"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    apagar_api_v1_enxovais__enxoval_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                enxoval_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    editar_api_v1_enxovais__enxoval_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                enxoval_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RespostasEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnxovalSaida"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    prever_api_v1_enxovais__enxoval_id__prever_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                enxoval_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RespostasEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnxovalSaida"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    marcar_api_v1_enxovais__enxoval_id__linhas__chave__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                enxoval_id: string;
                /** @description <slug>:<tamanho>:<variante>, ex.: body:P:frio */
                chave: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarcacaoEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnxovalSaida"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    completar_api_v1_enxovais__enxoval_id__linhas__chave__completar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                enxoval_id: string;
                /** @description <slug>:<tamanho>:<variante>, ex.: body:P:frio */
                chave: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompletarEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnxovalSaida"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    exportar_csv_api_v1_enxovais__enxoval_id__exportar_csv_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                enxoval_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    exportar_xlsx_api_v1_enxovais__enxoval_id__exportar_xlsx_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                enxoval_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    exportar_pdf_api_v1_enxovais__enxoval_id__exportar_pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                enxoval_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ler_api_v1_perfil_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__rotas__perfil__PerfilSaida"];
                };
            };
        };
    };
    salvar_avatar_api_v1_perfil_avatar_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AvatarEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__rotas__perfil__PerfilSaida"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
